### ISSUE TITLE
Integration with React Styleguidist

### ISSUE THREAD

**Issue by ginniecodes** [MedanoSoft/sand-ui#5]
TO DO:
Document Sand UI components with [React Styleguidist](https://github.com/styleguidist/react-styleguidist)

Sand UI needs a cute (and descriptive) documentation 😻 what about React Styleguidist for it?

**Comment by davidsonsns** [comment]
I was interested to study [Styleguide](https://react-styleguidist.js.org/). So I found the idea of @jhia  interesting and did the test.
In my opinion it makes it easier to view the properties. And its implementation is very simple.

If they agree with this integration I will finalize the components. tks

**Comment by ginniecodes** [comment]
Of course!, thanks and go ahead 👍
